export const products = [
  {
    _id: "1",
    name: "Airpods wireless bluetooth headphone",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality audio offering.",
    brand: "Apple",
    category: "Electronics",
    price: 89.0,
    countInStock: 10,
    rating: 5,
    numReviews: 12,
    image: "https://api.slingacademy.com/public/sample-photos/1.jpeg",
  },
  {
    _id: "2",
    name: "Samsung Galaxy S21",
    description:
      "Powerful smartphone with a stunning display, advanced camera system, and fast performance.",
    brand: "Samsung",
    category: "Electronics",
    price: 799.99,
    countInStock: 15,
    rating: 4.8,
    numReviews: 18,
    image: "https://api.slingacademy.com/public/sample-photos/2.jpeg",
  },
  {
    _id: "3",
    name: "Dell XPS 13 Laptop",
    description:
      "Ultra-portable laptop with a borderless InfinityEdge display and high-performance hardware.",
    brand: "Dell",
    category: "Electronics",
    price: 1299.99,
    countInStock: 8,
    rating: 3.5,
    numReviews: 22,
    image: "https://api.slingacademy.com/public/sample-photos/3.jpeg",
  },
  {
    _id: "4",
    name: "Sony WH-1000XM4 Wireless Headphones",
    description:
      "Industry-leading noise-canceling headphones with exceptional sound quality and comfort.",
    brand: "Sony",
    category: "Electronics",
    price: 349.99,
    countInStock: 5,
    rating: 4.9,
    numReviews: 25,
    image: "https://api.slingacademy.com/public/sample-photos/4.jpeg",
  },
  {
    _id: "5",
    name: "Canon EOS 5D Mark IV Camera",
    description:
      "Professional-grade DSLR camera with a full-frame sensor, 4K video recording, and advanced autofocus.",
    brand: "Canon",
    category: "Electronics",
    price: 2499.99,
    countInStock: 3,
    rating: 4.6,
    numReviews: 15,
    image: "https://api.slingacademy.com/public/sample-photos/5.jpeg",
  },
  {
    _id: "6",
    name: "LG OLED C1 65-inch 4K TV",
    description:
      "Premium OLED TV with stunning picture quality, Dolby Vision, and webOS smart platform.",
    brand: "LG",
    category: "Electronics",
    price: 1999.99,
    countInStock: 7,
    rating: 4.8,
    numReviews: 20,
    image: "https://api.slingacademy.com/public/sample-photos/6.jpeg",
  },
  {
    _id: "7",
    name: "Bose QuietComfort 35 II Wireless Headphones",
    description:
      "Comfortable over-ear headphones with excellent noise cancellation and impressive audio performance.",
    brand: "Bose",
    category: "Electronics",
    price: 299.99,
    countInStock: 12,
    rating: 4.7,
    numReviews: 30,
    image: "https://api.slingacademy.com/public/sample-photos/7.jpeg",
  },
  {
    _id: "8",
    name: "Microsoft Surface Pro 7",
    description:
      "Versatile 2-in-1 laptop with a detachable keyboard, touch screen, and powerful processing.",
    brand: "Microsoft",
    category: "Electronics",
    price: 899.99,
    countInStock: 9,
    rating: 4.5,
    numReviews: 14,
    image: "https://api.slingacademy.com/public/sample-photos/8.jpeg",
  },
  {
    _id: "9",
    name: "Fitbit Charge 4 Fitness Tracker",
    description:
      "Advanced fitness tracker with built-in GPS, heart rate monitoring, and sleep tracking.",
    brand: "Fitbit",
    category: "Electronics",
    price: 149.99,
    countInStock: 20,
    rating: 4.6,
    numReviews: 28,
    image: "https://api.slingacademy.com/public/sample-photos/9.jpeg",
  },
  {
    _id: "10",
    name: "KitchenAid Stand Mixer",
    description:
      "Powerful stand mixer for baking and cooking, with various attachments for versatile use.",
    brand: "KitchenAid",
    category: "Appliances",
    price: 349.99,
    countInStock: 6,
    rating: 4.9,
    numReviews: 32,
    image: "https://api.slingacademy.com/public/sample-photos/10.jpeg",
  },
];
